name: Daily Checkin with Python

on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间0点（北京时间8点）
  workflow_dispatch:      # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入仓库
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整提交历史
          token: ${{ secrets.DAILY_CHECKIN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.DAILY_CHECKIN }}  # 将 token 设置为环境变量
        run: python checkin.py
